language: cpp
sudo: required
compiler:
- g++
os:
- linux
before_install:
- echo $LANG
- echo $LC_ALL
- chmod u+x ./scripts/dependencies.sh
- ./scripts/dependencies.sh
script:
- ./scripts/3-codegen.sh
branches:
  only:
    - master
